name: Releasing with Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      
    steps:
      - id: checkout-step
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: setup-node-step
        name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'npm' # Agora podemos usar cache para acelerar!

      - id: setup-dotnet-step
        name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      # CORREÇÃO: Instala as dependências definidas no package.json localmente
      # Isso cria a pasta node_modules e o package-lock.json
      - id: install-dependencies-step
        name: Install Release Tools
        run: npm install

      - id: verify-step
        name: Verify .NET dependencies
        run: dotnet restore

      - id: semantic-release-step
        name: Release with Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        # Como instalamos localmente, o npx achará tudo automaticamente
        run: npx semantic-release
